// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Q2.Models;

public partial class Service
{
    public int ServiceId { get; set; }

    public string RoomTitle { get; set; }

    public string FeeType { get; set; }

    public decimal Price { get; set; }

    public string Status { get; set; }

    public string Description { get; set; }
}