// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Q2.Models;

public partial class Broker
{
    public int BrokerId { get; set; }

    public string FullName { get; set; }

    public string Phone { get; set; }

    public virtual ICollection<Contract> Contracts { get; set; } = new List<Contract>();
}