// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using Q2.Validations;
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;

namespace Q2.Models;

public partial class Contract
{
    public int ContractId { get; set; }
    [Required]

    public string ContractTitle { get; set; }
    [Required]
    public string PropertyType { get; set; }
    [Required]
    public DateOnly SigningDate { get; set; }
    [Required]
    public DateOnly ExpirationDate { get; set; }
    [Required]
    public int BrokerId { get; set; }
    [Required]
    public decimal Value { get; set; }

    public virtual Broker Broker { get; set; }
}