// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Q2.Models;

public partial class Employee
{
    public int EmployeeId { get; set; }

    public string EmployeeName { get; set; }

    public string Position { get; set; }

    public DateOnly HireDate { get; set; }

    public int DepartmentId { get; set; }

    public virtual Department Department { get; set; }
}